import React, { createContext, useContext, useState, useEffect } from 'react';

type Locale = 'English' | 'Bengali' | 'Hindi' | 'Arabic' | 'Spanish';

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const translations: Record<Locale, Record<string, string>> = {
  English: {
    'home': 'Home',
    'tasks': 'Tasks',
    'rewards': 'Rewards',
    'history': 'History',
    'account': 'Account',
    'balance': 'Balance',
    'points': 'Points',
    'withdraw': 'Withdraw',
    'refer': 'Refer',
    'support': 'Support',
    'logout': 'Sign Out',
    'loading': 'Loading...',
    'search': 'Search',
    'notifications': 'Notifications',
    'language': 'Language',
    'password': 'Password',
    'bank_info': 'Bank Info',
    'privacy': 'Privacy',
    'help': 'Help Center',
    'dashboard': 'Dashboard',
    'earning_tasks': 'Earning Tasks',
    'support_info': 'Support Info',
    'payout_info': 'Payout Info',
    'our_network': 'Our Network',
    'jobs_tasks': 'Jobs & Tasks',
    'terms_of_use': 'Terms of Use',
    'privacy_shield': 'Privacy Shield',
    'ip_address': 'IP Address',
    'earnings': 'Earnings',
    'daily_checkin': 'Daily Check-in',
    'earn_extra_pts': 'Earn extra pts daily',
    'claim': 'Claim',
    'daily_quiz': 'Daily Quiz',
    'quiz_desc': 'Test your knowledge and earn rewards',
    'task_center': 'Task Center',
    'task_center_desc': 'Visit sites and watch videos',
    'refer_earn': 'Refer & Earn',
    'refer_earn_desc': 'Get 10% of their earnings',
    'growth_program': 'Growth Program',
    'invite_earn_title': 'Invite & Earn Points',
    'invite_earn_desc': 'Share your code with friends and get bonus',
    'platform': 'Platform',
    'governance': 'Governance',
    'reward_marketplace': 'Reward Marketplace',
    'daily_missions_desc': 'Complete simple tasks to earn major points',
    'no_active_tasks': 'No active tasks available',
    'check_back_later': 'Check back later for new updates',
    'verify_now': 'Verify Now',
    'verifying': 'Verifying',
    'wait': 'Wait',
    'withdrawal_center': 'Withdrawal Center',
    'current_balance': 'Current Balance',
    'point_converter': 'Point Converter',
    'rate': 'Rate',
    'points_to_burn': 'Points to Burn',
    'confirm_withdrawal': 'Confirm Withdrawal',
    'withdrawal_notice': 'Important Withdrawal Notice',
    'min': 'MIN',
    'page_not_found': 'Page Not Found',
    'page_not_found_desc': 'The requested information page does not exist or has been removed.',
    'return_home': 'Return Home',
    'login_title': 'Welcome to PointHub',
    'login_subtitle': 'Enter your credentials to access your dashboard',
    'email_label': 'Email Address',
    'password_label': 'Password',
    'signin_btn': 'Sign In',
    'not_member': 'Not a member?',
    'join_now': 'Join Now',
    'invalid_login': 'Invalid email or password',
    'my_referral_code': 'My Referral Code',
    'copy_code': 'Copy Code',
    'copied': 'Copied!',
    'referral_stats': 'Referral Stats',
    'level_1': 'Level 1 (Direct)',
    'level_2': 'Level 2 (Indirect)',
    'total_referrals': 'Total Referrals',
    'how_it_works': 'How it works?',
    'step_1_title': 'Invite Friends',
    'step_1_desc': 'Share your referral code with your friends.',
    'step_2_title': 'They Join',
    'step_2_desc': 'They create an account using your code.',
    'step_3_title': 'Earn Bonus',
    'step_3_desc': 'Get 10% of their earnings for life!',
    'points_history': 'Points History',
    'all_transactions': 'All Transactions',
    'withdrawal_history': 'Withdrawal History',
    'no_history': 'No transactions found',
    'type': 'Type',
    'amount': 'Amount',
    'status': 'Status',
    'date': 'Date',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'acc_preferences': 'Account & Preferences',
    'sec_support': 'Security & Support',
    'help_center': 'Help Center',
    'admin_panel': 'Admin Control Panel',
    'sign_out': 'Sign Out',
    'how_help': 'How can we help?',
    'search_faq': 'Search FAQ keywords...',
    'email_us': 'Email Us',
    'live_chat': 'Live Chat',
    'device_history_title': 'Device History',
    'active_conn': 'Active Connection',
    'this_device_active': 'This device is active',
    'device_model': 'Device Model',
    'os_platform': 'OS / Platform',
    'refresh_location': 'Refresh Live Location',
    'bank_method': 'Preferred Method',
    'bank_details': 'Account Number / Details',
    'save_bank': 'Save Bank Info',
    'set_pass': 'Set Account Password',
    'change_pass': 'Change Password',
    'new_pass': 'New Secure Password',
    'confirm_pass': 'Confirm New Password',
    'update_pass': 'Update Password',
    'privacy_safety': 'Privacy & Safety',
    'delete_account': 'Delete Account',
    'request_deletion': 'Request Account Deletion',
    'verified_earner': 'Verified Earner',
    'acc_management': 'Account Management',
    'bank_name': 'Bank Name',
    'acc_name': 'Account Holder Name',
    'acc_number': 'Account Number',
    'branch_routing': 'Branch/Routing (Opt)',
    'mobile_bank_num': 'Mobile Banking Number',
    'paypal_email': 'PayPal Email Address',
    'req_submitted': 'Request Submitted!',
    'view_history': 'View History',
    'daily_quests': 'Daily Quests',
    'active_tasks': 'Active Tasks',
    'reward_shop': 'Reward Shop',
    'shop': 'Shop',
    'completed': 'Completed',
    'in_progress': 'In Progress',
    'tasks_desc': 'Complete simple tasks to earn major points!',
    'no_tasks': 'No tasks available right now.',
    'shop_desc': 'Redeem your hard earned points for epic rewards!',
    'check_back': 'Check back later for new offers.',
    'start_task': 'Start Task',
    'claimed': 'Claimed',
    'select_payout': 'Select Payout Method',
    'menu': 'Menu',
    'profile': 'Profile',
    'total': 'Total',
    'joined': 'Joined',
    'official_app': 'Official App',
    'app_desc': 'Download our native application for faster access and exclusive rewards.',
    'download_now': 'Download Now',
    'network_connected': 'Network Connected',
    'verifying_human': 'Verifying Human Presence',
    'enable_reward': 'Enable Reward',
    'accessing_reward': 'Accessing Reward Pool',
    'cancel': 'Cancel',
    'manage': 'Manage',
    'danger_zone': 'Danger Zone',
    'updated': 'Updated',
    'recently': 'Recently',
    'share_page': 'Share Page',
    'verify_info': 'Verify Information',
    'need_help': 'Need Help?',
    'news': 'News',
    'done': 'Done',
    'l1_l2_network': 'L1 & L2 Network',
    'sponsored': 'Sponsored Result',
    'get_rewards_now': 'Get Exclusive Rewards Now!',
    'click_reveal': 'Bonus code reveal',
    'visit_offer': 'Visit Offer',
    'interactive': 'Interactive',
    'hot': 'HOT',
    'lucky': 'LUCKY',
    'spin_desc': 'Spin to win up to 500 points',
    'popular': 'POPULAR',
    'rights_reserved': 'All Rights Reserved',
    'welcome_back': 'Welcome back,',
    'see_all': 'See All',
    'daily_bonus': 'Daily Bonus',
    'spin_wheel': 'Spin Wheel',
    'quick_stats': 'Quick Stats',
    'task_list': 'Task List',
    'task_available': 'Tasks Available',
    'verify': 'Verify',
    'verified': 'Verified',
    'pending': 'Pending',
    'min_withdrawal_error': 'Minimum withdrawal is',
    'insufficient_points': 'Insufficient points',
    'fill_bank_details': 'Please fill required bank details',
    'fill_all_fields': 'Please fill all fields',
    'something_wrong': 'Something went wrong',
    'req_processing_desc': 'Your withdrawal request is being processed. It usually takes 24-48 hours to approve.',
    'payout_time_window': '24-48h Approval Window',
    'compliance_security': 'Compliance & Security',
    'compliance_desc': 'All withdrawal requests undergo systematic fraud checks via IP Detection and Network Analysis. Providing false account details may result in permanent forfeiture of accumulated points. Please ensure your payout method is active and verified before requesting funds.',
    'withdrawals_disabled': 'Withdrawals are temporarily disabled for your account. Please contact support.',
  },
  Bengali: {
    'home': 'হোম',
    'tasks': 'টাস্ক',
    'rewards': 'পুরস্কার',
    'history': 'ইতিহাস',
    'account': 'অ্যাকাউন্ট',
    'balance': 'ব্যালেন্স',
    'points': 'পয়েন্ট',
    'withdraw': 'টাকা তুলুন',
    'refer': 'রেফার',
    'support': 'সহায়তা',
    'logout': 'লগ আউট',
    'loading': 'লোড হচ্ছে...',
    'search': 'খুঁজুন',
    'notifications': 'নোটিফিকেশন',
    'language': 'ভাষা',
    'password': 'পাসওয়ার্ড',
    'bank_info': 'ব্যাংক তথ্য',
    'privacy': 'গোপনীয়তা',
    'help': 'সহায়তা কেন্দ্র',
    'dashboard': 'ড্যাশবোর্ড',
    'earning_tasks': 'উপার্জন টাস্ক',
    'support_info': 'সহায়তা তথ্য',
    'payout_info': 'পেমেন্ট তথ্য',
    'our_network': 'আমাদের নেটওয়ার্ক',
    'jobs_tasks': 'কাজ ও টাস্ক',
    'terms_of_use': 'ব্যবহারের শর্তাবলী',
    'privacy_shield': 'প্রাইভেসি শিল্ড',
    'ip_address': 'আইপি ঠিকানা',
    'earnings': 'উপার্জন',
    'daily_checkin': 'দৈনিক চেক-ইন',
    'earn_extra_pts': 'প্রতিদিন অতিরিক্ত পয়েন্ট পান',
    'claim': 'দাবি করুন',
    'daily_quiz': 'দৈনিক কুইজ',
    'quiz_desc': 'আপনার জ্ঞান পরীক্ষা করুন এবং পুরস্কার জিতুন',
    'task_center': 'টাস্ক সেন্টার',
    'task_center_desc': 'সাইট ভিজিট করুন এবং ভিডিও দেখুন',
    'refer_earn': 'রেফার ও আয়',
    'refer_earn_desc': 'তাদের উপার্জনের ১০% পান',
    'growth_program': 'গ্রোথ প্রোগ্রাম',
    'invite_earn_title': 'বন্ধুদের আমন্ত্রণ জানান এবং পয়েন্ট পান',
    'invite_earn_desc': 'আপনার কোড বন্ধুদের সাথে শেয়ার করুন এবং বোনাস পান',
    'platform': 'প্ল্যাটফর্ম',
    'governance': 'পরিচালনা',
    'reward_marketplace': 'রিওয়ার্ড মার্কেটপ্লেস',
    'daily_missions_desc': 'পয়েন্ট অর্জন করতে সহজ কাজগুলো সম্পন্ন করুন',
    'no_active_tasks': 'বর্তমানে কোন কাজ নেই',
    'check_back_later': 'নতুন আপডেটের জন্য পরে চেক করুন',
    'verify_now': 'যাচাই করুন',
    'verifying': 'যাচাই করা হচ্ছে',
    'wait': 'অপেক্ষা করুন',
    'withdrawal_center': 'উইথড্রয়াল সেন্টার',
    'current_balance': 'বর্তমান ব্যালেন্স',
    'point_converter': 'পয়েন্ট কনভার্টার',
    'rate': 'রেট',
    'points_to_burn': 'পয়েন্ট উইথড্র',
    'confirm_withdrawal': 'উইথড্রয়াল নিশ্চিত করুন',
    'withdrawal_notice': 'গুরুত্বপূর্ণ উইথড্রয়াল নোটিশ',
    'min': 'নুন্যতম',
    'page_not_found': 'পেজ পাওয়া যায়নি',
    'page_not_found_desc': 'আপনার অনুরোধ করা পেজটি পাওয়া যায়নি বা সরিয়ে ফেলা হয়েছে।',
    'return_home': 'হোমে ফিরে যান',
    'login_title': 'PointHub-এ স্বাগতম',
    'login_subtitle': 'আপনার অ্যাকাউন্টে লগইন করতে তথ্য দিন',
    'email_label': 'ইমেল ঠিকানা',
    'password_label': 'পাসওয়ার্ড',
    'signin_btn': 'লগইন করুন',
    'not_member': 'অ্যাকাউন্ট নেই?',
    'join_now': 'নতুন অ্যাকাউন্ট তৈরি করুন',
    'invalid_login': 'ভুল ইমেল বা পাসওয়ার্ড',
    'my_referral_code': 'আমার রেফারাল কোড',
    'copy_code': 'কোড কপি করুন',
    'copied': 'কপি হয়েছে!',
    'referral_stats': 'রেফারাল পরিসংখ্যান',
    'level_1': 'লেভেল ১ (সরাসরি)',
    'level_2': 'লেভেল ২ (পরোক্ষ)',
    'total_referrals': 'মোট রেফারাল',
    'how_it_works': 'কিভাবে এটি কাজ করে?',
    'step_1_title': 'বন্ধুদের আমন্ত্রণ জানান',
    'step_1_desc': 'আপনার বন্ধুদের সাথে আপনার রেফারাল কোড শেয়ার করুন।',
    'step_2_title': 'তারা যুক্ত হবে',
    'step_2_desc': 'তারা আপনার কোড ব্যবহার করে একটি অ্যাকাউন্ট তৈরি করবে।',
    'step_3_title': 'বোনাস পান',
    'step_3_desc': 'তাদের আজীবন উপার্জনের ১০% বোনাস পাবেন!',
    'points_history': 'পয়েন্টের ইতিহাস',
    'all_transactions': 'সকল লেনদেন',
    'withdrawal_history': 'উইথড্রয়াল ইতিহাস',
    'no_history': 'কোন লেনদেন পাওয়া যায়নি',
    'type': 'ধরণ',
    'amount': 'পরিমাণ',
    'status': 'অবস্থা',
    'date': 'তারিখ',
    'approved': 'অনুমোদিত',
    'rejected': 'প্রত্যাখ্যাত',
    'acc_preferences': 'অ্যাকাউন্ট ও সেটিংস',
    'sec_support': 'নিরাপত্তা ও সহায়তা',
    'help_center': 'হেল্প সেন্টার',
    'admin_panel': 'অ্যাডমিন প্যানেল',
    'sign_out': 'লগআউট করুন',
    'how_help': 'কিভাবে আমরা সাহায্য করতে পারি?',
    'search_faq': 'প্রশ্ন খুঁজুন...',
    'email_us': 'ইমেল করুন',
    'live_chat': 'লাইভ চ্যাট',
    'device_history_title': 'ডিভাইসের ইতিহাস',
    'active_conn': 'সক্রিয় সংযোগ',
    'this_device_active': 'এই ডিভাইসটি সক্রিয়',
    'device_model': 'ডিভাইস মডেল',
    'os_platform': 'ওএস / প্ল্যাটফর্ম',
    'refresh_location': 'অবস্থান আপডেট করুন',
    'bank_method': 'পছন্দসই মাধ্যম',
    'bank_details': 'অ্যাকাউন্ট নম্বর / বিস্তারিত',
    'save_bank': 'তথ্য সংরক্ষণ করুন',
    'set_pass': 'পাসওয়ার্ড সেট করুন',
    'change_pass': 'পাসওয়ার্ড পরিবর্তন',
    'new_pass': 'নতুন পাসওয়ার্ড',
    'confirm_pass': 'পাসওয়ার্ড নিশ্চিত করুন',
    'update_pass': 'আপডেট করুন',
    'privacy_safety': 'গোপনীয়তা ও নিরাপত্তা',
    'delete_account': 'অ্যাকাউন্ট মুছে ফেলুন',
    'request_deletion': 'অ্যাকাউন্ট মুছে ফেলার অনুরোধ করুন',
    'verified_earner': 'ভেরিফাইড ইউজার',
    'acc_management': 'অ্যাকাউন্ট ম্যানেজমেন্ট',
    'bank_name': 'ব্যাংকের নাম',
    'acc_name': 'অ্যাকাউন্ট হোল্ডারের নাম',
    'acc_number': 'অ্যাকাউন্ট নম্বর',
    'branch_routing': 'ব্রাঞ্চ/রাউটিং (ঐচ্ছিক)',
    'mobile_bank_num': 'মোবাইল ব্যাংকিং নম্বর',
    'paypal_email': 'পেপ্যাল ইমেল অ্যাড্রেস',
    'req_submitted': 'অনুরোধ জমা দেওয়া হয়েছে!',
    'view_history': 'ইতিহাস দেখুন',
    'daily_quests': 'দৈনিক কাজ',
    'active_tasks': 'সক্রিয় কাজ',
    'reward_shop': 'রিওয়ার্ড শপ',
    'shop': 'শপ',
    'completed': 'সম্পন্ন',
    'in_progress': 'চলমান',
    'tasks_desc': 'পয়েন্ট অর্জন করতে সহজ কাজগুলো সম্পন্ন করুন!',
    'no_tasks': 'বর্তমানে কোন কাজ উপলব্ধ নেই।',
    'shop_desc': 'আপনার অর্জিত পয়েন্ট দিয়ে পুরস্কার কিনুন!',
    'check_back': 'নতুন অফারের জন্য পরে চেক করুন।',
    'start_task': 'কাজ শুরু করুন',
    'claimed': 'দাবিকৃত',
    'select_payout': 'পেমেন্ট মেথড সিলেক্ট করুন',
    'menu': 'মেনু',
    'profile': 'প্রোফাইল',
    'total': 'মোট',
    'joined': 'জয়েন করেছেন',
    'official_app': 'অফিসিয়াল অ্যাপ',
    'app_desc': 'দ্রুত অ্যাক্সেস এবং এক্সক্লুসিভ রিওয়ার্ডের জন্য আমাদের অ্যাপ ডাউনলোড করুন।',
    'download_now': 'ডাউনলোড করুন',
    'network_connected': 'নেটওয়ার্ক সংযুক্ত',
    'verifying_human': 'হিউম্যান ভেরিফিকেশন',
    'enable_reward': 'রিওয়ার্ড সক্রিয় করুন',
    'accessing_reward': 'রিওয়ার্ড পুল অ্যাক্সেস করা হচ্ছে',
    'cancel': 'বাতিল',
    'manage': 'ম্যানেজ',
    'danger_zone': 'ডেঞ্জার জোন',
    'updated': 'আপডেট করা হয়েছে',
    'recently': 'সম্প্রতি',
    'share_page': 'পেজ শেয়ার করুন',
    'verify_info': 'তথ্য যাচাই করুন',
    'need_help': 'সাহায্য প্রয়োজন?',
    'news': 'খবর',
    'done': 'সম্পন্ন',
    'l1_l2_network': 'L1 এবং L2 নেটওয়ার্ক',
    'sponsored': 'স্পন্সরড রেজাল্ট',
    'get_rewards_now': 'এক্সক্লুসিভ রিওয়ার্ড জিতে নিন!',
    'click_reveal': 'বোনাস কোড দেখতে ক্লিক করুন',
    'visit_offer': 'অফার দেখুন',
    'interactive': 'ইন্টারেক্টিভ',
    'hot': 'হট',
    'lucky': 'লাকি',
    'spin_desc': 'স্পিন করে ৫০০ পয়েন্ট পর্যন্ত জিতুন',
    'popular': 'জনপ্রিয়',
    'rights_reserved': 'সর্বস্বত্ব সংরক্ষিত',
    'welcome_back': 'স্বাগতম,',
    'see_all': 'সব দেখুন',
    'daily_bonus': 'দৈনিক বোনাস',
    'spin_wheel': 'স্পিন হুইল',
    'quick_stats': 'সংক্ষিপ্ত তথ্য',
    'task_list': 'কাজের তালিকা',
    'task_available': 'কাজ উপলব্ধ',
    'verify': 'যাচাই করুন',
    'verified': 'যাচাইকৃত',
    'pending': 'অপেক্ষমান',
    'min_withdrawal_error': 'সর্বনিম্ন উত্তোলন হলো',
    'insufficient_points': 'পর্যাপ্ত পয়েন্ট নেই',
    'fill_bank_details': 'অনুগ্রহ করে ব্যাংকের সঠিক তথ্য দিন',
    'fill_all_fields': 'সবগুলো ঘর পূরণ করুন',
    'something_wrong': 'কিছু একটা ভুল হয়েছে',
    'req_processing_desc': 'আপনার টাকা উত্তোলনের অনুরোধটি প্রক্রিয়াধীন রয়েছে। এটি সাধারণত ২৪-৪৮ ঘণ্টা সময় নেয়।',
    'payout_time_window': '২৪-৪৮ ঘণ্টার মধ্যে অনুমোদন',
    'compliance_security': 'সম্মতি ও নিরাপত্তা',
    'compliance_desc': 'সকল উত্তোলনের অনুরোধ আইপি ডিটেকশন এবং নেটওয়ার্ক বিশ্লেষণের মাধ্যমে পদ্ধতিগতভাবে জালিয়াতি পরীক্ষা করা হয়। ভুল অ্যাকাউন্টের বিবরণ প্রদান করলে অর্জিত পয়েন্ট স্থায়ীভাবে বাজেয়াপ্ত হতে পারে। পেমেন্ট পাওয়ার জন্য আপনার মেথডটি সক্রিয় এবং যাচাইকৃত কিনা তা নিশ্চিত করুন।',
    'withdrawals_disabled': 'আপনার অ্যাকাউন্টের জন্য টাকা উত্তোলন সাময়িকভাবে বন্ধ আছে। সহায়তার জন্য যোগাযোগ করুন।',
  },
  Hindi: {
    'home': 'होम',
    'tasks': 'कार्य',
    'rewards': 'पुरस्कार',
    'history': 'इतिहास',
    'account': 'खाता',
    'balance': 'संतुलन',
    'points': 'अंक',
    'withdraw': 'निकालें',
    'refer': 'रेফার करें',
    'support': 'सहायता',
    'logout': 'साइन আউট',
  },
  Arabic: {
    'home': 'الرئيسية',
    'tasks': 'المهام',
    'rewards': 'المكافآت',
    'history': 'السجل',
    'account': 'الحساب',
    'balance': 'الرصيد',
    'points': 'نقاط',
    'withdraw': 'سحب',
    'refer': 'إحالة',
    'support': 'الدعم',
    'logout': 'تسجيل الخروج',
  },
  Spanish: {
    'home': 'Inicio',
    'tasks': 'Tareas',
    'rewards': 'Premios',
    'history': 'Historial',
    'account': 'Cuenta',
    'balance': 'Saldo',
    'points': 'Puntos',
    'withdraw': 'Retirar',
    'refer': 'Referir',
    'support': 'Soporte',
    'logout': 'Cerrar sesión',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>(() => {
    const saved = localStorage.getItem('app_locale');
    return (saved as Locale) || 'English';
  });

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('app_locale', newLocale);
  };

  const t = (key: string): string => {
    return translations[locale][key] || translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
